version: "3"
services:
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        ports:
            - "9092:9092"
        environment:      
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: 'PLAINTEXT://:9092'
            KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://127.0.0.1:9092'
            ALLOW_PLAINTEXT_LISTENER: 'yes'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_CREATE_TOPICS: 'VideoTopic:1:1,UserTopic:1:1' 
        depends_on:
            - zookeeper