version: "3"
services:
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        ports:
            - "9092:9092"
        environment:      
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: 'INTERNAL://:9092'
            KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://:9092'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT'
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_CREATE_TOPICS: 'Topic1:1:1,Topic2:1:1'    
        depends_on:
            - zookeeper